### ISSUE TITLE
Логотип организации

### ISSUE THREAD

**Issue by kugimiya** [U-Me-Chan/pissykaka#3]
Кароче, такое дело. Этот issue не относится к бекенду, просто глобальных issues у оргазаций нет.
Суть: gravatar вместо логотипа прикольная задумка, однако предлагаю запилить какой-нибудь логотип к оргазации U-Me-Chan на Github.

Предлагаю вот такой, наляпал на скорую руку:
<img width="512" alt="Group 12" src="https://user-images.githubusercontent.com/8094908/185786385-5954d146-3e43-404a-9893-469cfa0dd8ce.png">

Нюансы которые учёл в логотипе: 
- оставил место по бокам и углам, потому что GH углы скругляет
- букву "U" сделал самой большой, потому что шлейф "Ю" как маскота-литерала
- ширину слова "group" довёл до ширины слова "U-me"
- на фоне цвет Gentoo-wiki (это линейный градиент)

**Comment by ridouchire** [comment]
@kugimiya, спасибо! Применила.
